### ISSUE TITLE
Hard Killing node in cluster using EventBus causes NullPointerException

### ISSUE THREAD

**Issue by whoisjake** [vert-x3/vertx-hazelcast#11]
Incredibly easy to reproduce...

I created a dummy Verticle that uses the EventBus... Did a Maven "fat-jar" project, included Vertx 3.0.0 and Hazelcast 3.4.

**NOTE:** This bug does *not* reproduce if you don't use an EventBus. It's definitely EventBus related.

The verticle was simply:

```java
package com.test;

import io.vertx.core.eventbus.EventBus;
import io.vertx.core.AbstractVerticle;

public class FailureVerticle extends AbstractVerticle {
  // Called when verticle is deployed
  public void start() {
    EventBus eb = vertx.eventBus();
    eb.consumer("broadcasts", message -> {
      System.out.println("got: " + message.body());
      message.reply("pong");
    });

    vertx.setPeriodic(1000, (l) -> {
      eb.send("broadcasts", "ping");
    });
  }
}
```

Started 3 instances in separate terminals
```bash
./bin/start
```

kill one off
```
jps | grep -v Jps | head -n 1 | xargs kill -9
```

Then get this
```
Aug 05, 2015 11:32:00 AM com.hazelcast.spi.impl.EventServiceImpl
SEVERE: [X.X.X.X]:5701 [dev] [3.4] hz._hzInstance_1_dev.event-2 caught an exception while processing task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@22bb6975
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at io.vertx.core.impl.ConcurrentHashSet.remove(ConcurrentHashSet.java:79)
	at io.vertx.spi.cluster.hazelcast.impl.ChoosableSet.remove(ChoosableSet.java:57)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.removeEntry(HazelcastAsyncMultiMap.java:151)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.entryRemoved(HazelcastAsyncMultiMap.java:145)
	at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatch0(MultiMapEventsDispatcher.java:94)
	at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatchEntryEventData(MultiMapEventsDispatcher.java:68)
	at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatchEvent(MultiMapEventsDispatcher.java:39)
	at com.hazelcast.multimap.impl.MultiMapService.dispatchEvent(MultiMapService.java:339)
	at com.hazelcast.multimap.impl.MultiMapService.dispatchEvent(MultiMapService.java:64)
	at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:666)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)
```

Example project:
https://github.com/DevelopStuff/vertx-hazelcast-bug

**Comment by purplefox** [comment]
Vert.x 3.0.0 requires hazelcast 3.5, not 3.4

http://repo1.maven.org/maven2/io/vertx/vertx-hazelcast/3.0.0/vertx-hazelcast-3.0.0.pom

**Comment by whoisjake** [comment]
Ahoy! Thanks for pointing that out, not sure why I have that particular dep. in my own pom file... I'll double check that it works this week!
