### ISSUE TITLE
Health check may block the event loop

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hazelcast#142]
The cluster health check procedure can block the event loop and thus prevent the application from stopping.

```
WARNING: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5171 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:634)
	at app//com.hazelcast.internal.util.FutureUtil.executeWithDeadline(FutureUtil.java:389)
	at app//com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:270)
	at app//com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:240)
	at app//com.hazelcast.internal.partition.PartitionServiceProxy.isClusterSafe(PartitionServiceProxy.java:132)
	at app//io.vertx.spi.cluster.hazelcast.ClusterHealthCheck.lambda$createProcedure$0(ClusterHealthCheck.java:41)
	at app//io.vertx.spi.cluster.hazelcast.ClusterHealthCheck$$Lambda$1242/0x0000000840538c40.handle(Unknown Source)
	at app//io.vertx.ext.healthchecks.impl.DefaultProcedure.check(DefaultProcedure.java:46)
```

**Comment by tsegismont** [comment]
Closed in 42d32b4
