### ISSUE TITLE
Problems when cluster state changes

### ISSUE THREAD

**Issue by dprinov** [vert-x3/vertx-hazelcast#151]
### Version
4.2.3

### Context

We have a cluster with two nodes.
1) We pause one of the nodes and wait for the cluster to change its state. 
2) Unpause the node and wait for the cluster to change its state again. On this step a NPE is thrown:

`Exception in thread "hz.frosty_cori.cached.thread-7" java.lang.NullPointerException
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.stateChanged(HazelcastClusterManager.java:346)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:72)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:66)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:81)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:110)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:307)
	at com.hazelcast.internal.cluster.impl.operations.MergeClustersOp.lambda$run$0(MergeClustersOp.java:66)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
`
### Extra
After a quick look from our side we see that `VertxOptions::setHAEnabled` with `true` could prevent this NPE from happening.

**Comment by sfitts** [comment]
The issue appears to be that the code isn't checking to make sure that `nodeListener` is non-null prior to the invocation at line 346.  Every other invocation of the listener is guarded to protect against this, but not this one.  A workaround is to set a no-op node listener on the cluster manager instance.

Note that if you run with HA enabled you won't see this as the HA manager installs this listener.
