### ISSUE TITLE
NPE when putting nodeId to nodeInfoMap

### ISSUE THREAD

**Issue by anhptvolga** [vert-x3/vertx-hazelcast#173]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

vertx  4.4.0

### Context

I'm running vertx cluster version 4.3.7 in k8s.
I cannot start vertx cluster when I'm upgrade to 4.4.0.

### Extra

```
 java.util.concurrent.ExecutionException: java.lang.NullPointerException: Null key is not allowed!
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at com.ndl.cohub.heart.CohubHeartBoot.main(CohubHeartBoot.java:91)
Caused by: java.lang.NullPointerException: Null key is not allowed!
    at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:133)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
    at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$setNodeInfo$2(HazelcastClusterManager.java:196)
    at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
    at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
    at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsegismont** [comment]
Closed in ccfe8ce
