### ISSUE TITLE
ThrottlingTest may throw ConcurrentModificationException

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hazelcast#179]
```
2023-06-01T09:16:23.9981947Z Running io.vertx.spi.cluster.hazelcast.impl.ThrottlingTest
2023-06-01T09:16:29.0288568Z Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.023 sec <<< FAILURE! - in io.vertx.spi.cluster.hazelcast.impl.ThrottlingTest
2023-06-01T09:16:29.0290953Z testInterval(io.vertx.spi.cluster.hazelcast.impl.ThrottlingTest)  Time elapsed: 5.022 sec  <<< ERROR!
2023-06-01T09:16:29.0291550Z java.util.ConcurrentModificationException: null
2023-06-01T09:16:29.0292079Z 	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
2023-06-01T09:16:29.0292688Z 	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
2023-06-01T09:16:29.0293235Z 	at io.vertx.spi.cluster.hazelcast.impl.ThrottlingTest.lambda$testInterval$3(ThrottlingTest.java:81)
```

**Comment by tsegismont** [comment]
Fixed in a2b3a9c19c2129ed265a4922c7d4e6abc312859d
