### ISSUE TITLE
EventLoop thread blocked on HazelcastLock.release()

### ISSUE THREAD

**Issue by chemist777** [vert-x3/vertx-hazelcast#23]
Vertx 3.2.1.
EventLoop thread blocked on HazelcastLock.release().

Stacktrace:
```
19:11:04.917 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5014 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.lang.Object.wait(Native Method) ~[na:1.8.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:299) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:247) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.getSafely(InvocationFuture.java:216) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.release(SemaphoreProxy.java:115) ~[hazelcast-3.5.2.jar:3.5.2]
	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.release(SemaphoreProxy.java:106) ~[hazelcast-3.5.2.jar:3.5.2]
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager$HazelcastLock.release(HazelcastClusterManager.java:388) ~[vertx-hazelcast-3.2.1.jar:na]
	....
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction$$Lambda$150/1550800554.handle(Unknown Source) ~[na:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335) ~[vertx-core-3.2.1.jar:na]
	at io.vertx.core.impl.ContextImpl$$Lambda$8/1067262186.run(Unknown Source) ~[na:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[netty-common-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.33.Final.jar:4.0.33.Final]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.8.0]
```

May be you forgot to write something like vertx.executeBlocking in Lock implementation.

**Comment by cescoffier** [comment]
Yes, `lock.release` is blocking. We may need to update the API to reflect this aspect:

```
lock.release() <- the current one would become deprecated
lock.release(Handler<Void>) <-async method
```

However, such a change would break the API of all cluster managers (we could provide a default implementation)

Another approach would be to keep `lock.release()` as it is Today but just changing the implementation to be non-locking. The main issue with this is the hidden meaning: the lock is not release when the method has returned.

@vietj, @pmlopes WDYT ?

**Comment by cescoffier** [comment]
As reference, in the HZ cluster manager, the lock is implemented using a `ISempaphore`: 
http://docs.hazelcast.org/docs/3.6/javadoc/com/hazelcast/core/ISemaphore.html

**Comment by vietj** [comment]
is it expected that lock.release() has released the lock after return or not ?

**Comment by cescoffier** [comment]
no, as the lock may not have been acquired before. It's up to the application to use the lock object consistently.

**Comment by vietj** [comment]
I think then it should be async and documented that it is async, and we would add an release(Handler<Void>) method if we need it later.

**Comment by purplefox** [comment]
+1 I think just wrapping it in executeBlocking should be sufficient
