### ISSUE TITLE
vertx-hazelcast isn't OSGi friendly

### ISSUE THREAD

**Issue by ANierbeck** [vert-x3/vertx-hazelcast#55]
The current jar/bundle lacks OSGi meta data regarding imports/exports of packages

**Comment by ANierbeck** [comment]
the following pull-request should fix that: 
https://github.com/vert-x3/vertx-hazelcast/pull/56

**Comment by cescoffier** [comment]
@tsegismont why did you revert ?

**Comment by tsegismont** [comment]
See #57

2017-02-17 8:49 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by gadieichhorn** [comment]
Hi all,
this is related to OSGi so I believe this is the right place to add my question.

I run vertx cluster under Karaf (OSGi) and I am getting this error when I try to use the eventbus.
```
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastServerID', exception: io.vertx.spi.cluster.hazelcast.impl.
HazelcastServerID not found by io.effectus.effectus-core-vertx [14]
        at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:130)[11:com.hazelcast:3.6.3]
        at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)[11:com.hazelcast:3.6.3]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)[11:com.hazelcast:3.6.3]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)[11:com.hazelcast:3.6.3]
        at com.hazelcast.map.impl.DataAwareEntryEvent.getValue(DataAwareEntryEvent.java:90)[11:com.hazelcast:3.6.3]
        at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.entryAdded(HazelcastAsyncMultiMap.java:130)[61:wrap_file__C__Users_gadei_development_github_effectus.io_effectus-data_data.jdbc_data.jdbc.test_data.jdbc.test.assembly_
target_assembly_system_io_vertx_vertx-hazelcast_3.4.0-SNAPSHOT_vertx-hazelcast-3.4.0-SNAPSHOT.jar:0.0.0]
        at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatch0(MultiMapEventsDispatcher.java:108)[11:com.hazelcast:3.6.3]
        at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatchEntryEventData(MultiMapEventsDispatcher.java:84)[11:com.hazelcast:3.6.3]
        at com.hazelcast.multimap.impl.MultiMapEventsDispatcher.dispatchEvent(MultiMapEventsDispatcher.java:55)[11:com.hazelcast:3.6.3]
        at com.hazelcast.multimap.impl.MultiMapService.dispatchEvent(MultiMapService.java:371)[11:com.hazelcast:3.6.3]
        at com.hazelcast.multimap.impl.MultiMapService.dispatchEvent(MultiMapService.java:65)[11:com.hazelcast:3.6.3]
        at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)[11:com.hazelcast:3.6.3]
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)[11:com.hazelcast:3.6.3]
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)[11:com.hazelcast:3.6.3]
Caused by: java.lang.ClassNotFoundException: io.vertx.spi.cluster.hazelcast.impl.HazelcastServerID not found by io.effectus.effectus-core-vertx [14]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)[org.apache.felix.framework-5.6.1.jar:]
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.6.1.jar:]
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)[org.apache.felix.framework-5.6.1.jar:]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_101]
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)[11:com.hazelcast:3.6.3]
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)[11:com.hazelcast:3.6.3]
        at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:68)[11:com.hazelcast:3.6.3]
        at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:119)[11:com.hazelcast:3.6.3]
        ... 13 more
```

as you can see I still have to wrap the vertx-hazelcast bundle, otherwise it complains about the wrong manifest version.

Am I missing a configuration or my class loading is not finding some vertx classes?

 appreciate any help

p.s. I can form a cluster and I can see the hazelcast node count change correctly, but the cluster manager will spit this error when I try to write a message to the bus

**Comment by gadieichhorn** [comment]
please see my solution here -> http://stackoverflow.com/a/42531968/148397

I ended up rolling the osgi hazelcast instance and adding the configuration from the vertx manual !
I used the hazelcast config to link the classloader to the vertx cluster manager and all works!

        Config hazelcastConfig = new Config("effectus-instance")
                .setClassLoader(HazelcastClusterManager.class.getClassLoader())

I hope this helps someone.
