### ISSUE TITLE
vertx.close() fails if clusterManager.leave() has been called first

### ISSUE THREAD

**Issue by kliakos** [vert-x3/vertx-hazelcast#69]
If I have explicitly initialized a HazelcastClusterManager, and call `HazelcastClusterManager.leave()`, a subsequent call to `vertx.close()` throws exception.

The reason I want to explicitly call `HazelcastClusterManager.leave()`, is to ensure that all events are handled until the node leaves the cluster and no more events are received by the node. Otherwise, calling `vertx.close()` first closes the event bus, which doesn't immediately inform the cluster/sender that this node is not longer active, and results to some messages timing out.

`SEVERE: Failed to remove sub
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:85)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:80)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:74)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.remove(ObjectMultiMapProxy.java:124)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$remove$4(HazelcastAsyncMultiMap.java:133)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by tsegismont** [comment]
The exception is expected as closing the cluster manager while Vert.x is still operating is illegal.

In general, it's a good idea to add retry mechanisms on send calls (if the operation is idempotent). You'd do that for timeout/no handlers errors.

If you want to make sure your node no longer receives messages, undeploy your verticles before closing Vert.x (make sure to complete the stop future only after the unregister method handler is invoked).

**Comment by kliakos** [comment]
Tried that also. Undeploying vertx while receiving messages, results in some messages timing out. It's the same as shutting down the event bus or unregistering the consumers.

The only 100% correct solution with no lost messages, is to leave the cluster, and when done, shut down vertx.

Maybe this should be the correct order of operations when closing vertx?

**Comment by tsegismont** [comment]
2017-03-20 23:59 GMT+01:00 Konstantinos Liakos <notifications@github.com>:

> Tried that also. Undeploying vertx while receiving messages, results in
> some messages timing out. It's the same as shutting down the event bus or
> unregistering the consumers.
>

Yes, sorry if that wasn't clear, I was suggesting undeploying verticles AND
retry on client side as the same time.


> The only 100% correct solution with no lost messages, is to leave the
> cluster, and when done, shut down vertx.
>

This is simply not possible with Vert.x The event bus is lightweight
messaging solution so if you need strong guarantees, consider using a MOM
(Artemis, RabbitMQ, ... etc).

See http://vertx.io/docs/vertx-core/java/#_best_effort_delivery
