### ISSUE TITLE
Interaction with the asyncmap puts request into ended state

### ISSUE THREAD

**Issue by robbieknuth** [vert-x3/vertx-hazelcast#70]
I'm attempting to use the asyncmap to cache certain aspects of requests. This is done in some middleware, then put onto the routing context, and then I call routingContext.next(). However interaction with the async map causes an exception:
`java.lang.IllegalStateException: Request has already been read`

Using the hazelcast's map directly does not cause this problem. Somehow the event loop is getting a "lasthttpcontent" object and closes the request. I believe this has something to do with the event loop, because even scheduling hazelcast's 'put' and 'get' on workers cause the same issue.

I've hacked up a repro here: https://gist.github.com/robbieknuth/67e46195b30c7f99b1d742e5af415887

The real meat and potatoes there is that the middleware interacts with the asyncmap. Then it calls routing context.next().

Using the repro, this is fine: `http://127.0.0.1:9000/without`
This blows up `http://127.0.0.1:9000/with`

Versions:
```
    compile group: 'io.vertx', name: 'vertx-hazelcast', version: '3.4.0'
    compile group: 'io.vertx', name: 'vertx-web', version: '3.4.0'
    compile group: 'io.vertx', name: 'vertx-core', version: '3.4.0'
```

Exception:
```
Apr 07, 2017 11:27:18 AM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:426)
	at io.vertx.core.http.impl.HttpServerRequestImpl.endHandler(HttpServerRequestImpl.java:239)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:57)
	at EntryPoint$Verticle.actualRoute(EntryPoint.java:122)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at EntryPoint$Verticle.lambda$null$3(EntryPoint.java:106)
	at EntryPoint$HandlerCallBackAdapter.setResult(EntryPoint.java:260)
	at EntryPoint$HandlerCallBackAdapter.onResponse(EntryPoint.java:249)
	at com.hazelcast.util.executor.DelegatingFuture$DelegatingExecutionCallback.onResponse(DelegatingFuture.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:127)
	at EntryPoint$VertxExecutorAdapter.lambda$execute$0(EntryPoint.java:287)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by robbieknuth** [comment]
Not this library's problem. You have to pause the request when you want to do async stuff.

https://github.com/vert-x3/vertx-web/issues/198
