### ISSUE TITLE
3.4.1 incompatibility with 3.3.3

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-hazelcast#72]
I have a `3.3.3` app which, after successfully joining a hazelcast cluster containing `3.4.1` nodes, attempts to send a clustered event bus message and gets the failure below.

```
2017-04-20T11:59:13.604-0500 [vert.x-eventloop-thread-7] ERROR i.v.c.e.i.c.ClusteredEventBus - Failed to send message
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastClusterNodeInfo', exception: io.vertx.spi.cluster.hazelcast.impl.HazelcastClusterNodeInfo
	at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:130) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.multimap.impl.operations.MultiMapResponse.getObjectCollection(MultiMapResponse.java:72) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.get(ObjectMultiMapProxy.java:116) ~[hazelcast-3.6.3.jar:3.6.3]
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$get$2(HazelcastAsyncMultiMap.java:96) ~[vertx-hazelcast-3.3.3.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:259) ~[vertx-core-3.3.3.jar:na]
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94) ~[vertx-core-3.3.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: io.vertx.spi.cluster.hazelcast.impl.HazelcastClusterNodeInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_91]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:68) ~[hazelcast-3.6.3.jar:3.6.3]
	at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:119) ~[hazelcast-3.6.3.jar:3.6.3]
	... 12 common frames omitted
```

**Comment by tsegismont** [comment]
This is expected, see https://github.com/vert-x3/wiki/wiki/3.4.0---Breaking-Changes#clustering

The change was needed to fix the cluster stability issues in case of data loss (too many nodes going down at once, for example).
