### ISSUE TITLE
when in same pc,it,s OK,but in different pc.error

### ISSUE THREAD

**Issue by felix-laofan** [vert-x3/vertx-hazelcast#88]
二月 24, 2018 11:37:24 上午 io.vertx.core.eventbus.impl.clustered.ConnectionHolder
警告: Connecting to server localhost:5614 failed
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:5614
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more

source code:

/**
 * 开启集群。负责向另外一个节点发消息。
 * @author Administrator
 *
 */
public class APPClusterSlave {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		Config config = new ClasspathXmlConfig("xmlconfig/simple-config.xml");
		ClusterManager mgr = new HazelcastClusterManager();
		VertxOptions options = new VertxOptions().setClusterManager(mgr);
		Vertx.clusteredVertx(options, res -> {
		  if (res.succeeded()) {
			System.out.println("ffffffffffffff");
		    Vertx vertx = res.result();
			vertx.eventBus().send("testMsg", "1111");
//		    vertx.setPeriodic(1000, id->{
////		    	vertx.eventBus().registerCodec(codec);
//		    	vertx.eventBus().send("testMsg", "laofan send::"+new Date().toGMTString());
//		    	vertx.eventBus().send("testMsg1", "laofan send::"+new Date().toGMTString());
//		    });
		  } else {
		    
		  }
		});
		
		
			
	}

}

public static void main(String[] args) {
//		Config config = new ClasspathXmlConfig("xmlconfig/simple-config.xml");
		ClusterManager mgr = new HazelcastClusterManager();
		VertxOptions options = new VertxOptions().setClusterManager(mgr);
		Vertx.clusteredVertx(options, res -> {
		  if (res.succeeded()) {
		    Vertx vertx = res.result();
		    vertx.eventBus().consumer("testMsg",str->{
		    		System.out.println("收到消息："+str.body());
		    		try {
						Thread.currentThread().sleep(1500);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
		    });
		    
		    vertx.eventBus().consumer("testMsg1",str->{
	    		System.out.println("收到消息1："+str.body());
	    		try {
					Thread.currentThread().sleep(1500);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	    });
		    
		  } else {
		    
		  }
		});
		
		
		
			
	}

**Comment by tsegismont** [comment]
Duplicates vert-x3/issues#332
